import 'package:masmas/constants/constant.dart';

class LocalizationMap {
  static Map<String, String> get codeEn => {
        "login_to_your_account": "Login To Your Account",
        "or_continue_with": "Or Continue With",
        "forgot_your_password": "Forgot Your Password",
        "email": "Email",
        "password": "Password",
        "login": "Login",
        "create_an_account": "Create an account",
        "sign_up_for_free": "Sign Up For Free",
        "anamwp": "Anamwp . . ",
        "keep_me_signed_in": "Keep Me Signed In",
        "email_me_about_special_pricing": "Email Me About Special Pricing",
        "create_account": "Create Account",
        "already_have_an_account": "already have an account?",
        "fill_in_your_bio_to_get_started": "Fill in your bio to get \nstarted",
        "this_data_will_be_displayed_in_your_account_profile_for_security":
            "This data will be displayed in your account \nprofile for security",
        "first_name": "First Name",
        "last_name": "Last Name",
        "mobile_number": "Mobile Number",
        "next": "Next",
        "payment_method": "Payment Method",
        "upload_your_photo_profile": "Upload Your Photo \nProfile",
        "set_your_location": "Set Your Location",
        "set_location": "Set Location",
        "your_location": "Your Location",
        "congrats": "Congrats!",
        "your_profile_is_ready_to_use": "Your profile is ready to use",
        "try_order": "Try Order",
        "enter_4_digit_verification_code": "Enter 4-digit \nVerification code",
        "enter_first_name": "Enter First name",
        "enter_last_name": "Enter last name",
        "enter_your_mobile_number": "Enter your mobile number",
        "password_reset_succesful": "Password reset succesful",
        "back": "Back",
        "forgot_password": "Forgot password?",
        "select_which_contact_details_should_we_use_to_reset_your_password":
            "Select which contact details should we \nuse to reset your password",
        "via_sms": "Via sms",
        "via_email": "Via email",
        "please_enter_your_pin_code": "Please enter your pin code",
        "enter_password": "Enter Password",
        "enter_email": "Enter Email",
        "please_enter_a_valid_email_address":
            "Please enter a valid email address",
        "reset_your_password_here": "Reset your password \nhere",
        "enter_your_new_password": "Enter your new password",
        "new_password": "New Password",
        "please_enter_new_password": "Please Enter New Password",
        "password_must_be_atleast_8_characters_long":
            "Password must be atleast 8 characters long",
        "password_not_match": "Password not match",
        "confirm_password": "Confirm Password",
        "find_your_comfort": "Find your Comfort",
        "food_here": "Food here",
        "here_you_can_find_a_chef_or_dish_for_every":
            "Here You Can find a chef or dish for every",
        "taste_and_color_enjoy": "taste and color.Enjoy!",
        "food_ninja_is_where_your": "Food Ninja is Where Your",
        "comfort_food_lives": "Comfort Food Lives",
        "enjoy_a_fast_and_smooth_food_delivery_at":
            "Enjoy a fast and smooth food delivery at",
        "your_doorstep": "your doorstep",
        "shipping": "Shipping",
        "place_my_order": "Place my order",
        "sub_total": "Sub-Total",
        "delivery_charge": "Delivery Charge",
        "discount": "Discount",
        "total": "Total",
        "order_details": "Order details",
        "confirm_order": "Confirm Order",
        "deliver_to": "Deliver To",
        "edit": "Edit",
        "payment": "Payment",
        "order_location": "Order Location",
        "ringing": "Ringing...",
        "okay_i_m_waiting": "Okay I'm waiting ",
        "thank_you_order_completed": "Thank You! \nOrder Completed",
        "thank_you_enjoy_your_meal": "Thank You! \nEnjoy your meal",
        "please_rate_your_last_driver": "Please rate your last Driver",
        "please_rate_your_food": "Please rate your food",
        "please_rate_your_restaurant": "Please rate your Restaurant",
        "leave_feedback": "Leave feedback",
        "chat": "Chat",
        "type": "Type",
        "location": "Location",
        "food": "Food",
        "search": "Search",
        "favorite": "Favorite",
        "proccess": "Proccess",
        "find_your_favorite_food": "Find Your \nFavorite Food ",
        "what_do_you_want_to_order": "What do you want to order?",
        "nearest_restaurant": "Nearest Restaurant",
        "view_more": "View More",
        "popular_menu": "Popular Menu",
        "view_all": "View All",
        "testimonials": "Testimonials",
        "popular": "Popular",
        "notification": "Notification",
        "you_have": "You Have",
        "voucher": " Voucher",
        "add_to_cart": "Add to Cart",
        "popular_restaurant": "Popular Restaurant",
        "check_out": "Check out",
        "voucher_promo": "Voucher Promo",
        "home": "Home",
        "profile": "Profile",
        "cart": "Cart",
        "member_gold": "Member Gold",
        "buy_again": "Buy Again",
        "current_location": "Current Location",
        "form_gallery": "From Gallery ",
        "from_camera": "From Camera",
        "enter_name": "Enter name",
        "code_send_to": " Code send to",
        "this_code_will_expired_in": " This code will \nexpired in",
        "submit": "Submit",
        "skip": "Skip",
        "added": "Added",
        "enter_message": "Enter Message",
        "press_again_to_exit": "Press again to exit"
      };
  static Map<String, String> get codeAr => {
        "login_to_your_account": "تسجيل الدخول إلى حسابك",
        "or_continue_with": "أو الاستمرار مع",
        "forgot_your_password": "نسيت كلمة السر",
        "email": "بريد إلكتروني",
        "password": "كلمة المرور",
        "login": "تسجيل الدخول",
        "create_an_account": "إنشاء حساب",
        "sign_up_for_free": "سجل مجانا",
        "anamwp": "انامب . .",
        "keep_me_signed_in": "ابقني مسجل",
        "email_me_about_special_pricing":
            "راسلني عبر البريد الإلكتروني بخصوص الأسعار الخاصة",
        "create_account": "إنشاء حساب",
        "already_have_an_account": "هل لديك حساب؟",
        "fill_in_your_bio_to_get_started": "املأ سيرتك الذاتية للبدء",
        "this_data_will_be_displayed_in_your_account_profile_for_security":
            "سيتم عرض هذه البيانات في ملف تعريف حسابك للأمان",
        "first_name": "الاسم الأول",
        "last_name": "اسم العائلة",
        "mobile_number": "رقم الهاتف المحمول",
        "next": "التالي",
        "payment_method": "طريقة الدفع او السداد",
        "upload_your_photo_profile": "قم بتحميل ملف تعريف الصور   \nالخاص بك",
        "set_your_location": "حدد موقعك",
        "set_location": "تحديد المكان",
        "congrats": "!تهاني",
        "your_profile_is_ready_to_use": "ملفك الشخصي جاهز للاستخدام",
        "try_order": "حاول الطلب",
        "enter_4_digit_verification_code": "رمز التحقق أدخل 4 أرقا",
        "enter_first_name": "أدخل الاسم الأول",
        "enter_last_name": "إدخال اسم آخر",
        "enter_your_mobile_number": "أدخل رقم هاتفك المحمول",
        "password_reset_succesful": "تمت إعادة تعيين كلمة المرور بنجاح",
        "back": "خلف",
        "forgot_password": "هل نسيت كلمة السر؟",
        "select_which_contact_details_should_we_use_to_reset_your_password":
            "حدد تفاصيل الاتصال التي يجب أن نستخدمها لإعادة \n تعيين كلمة المرور الخاصة بك",
        "via_sms": "عبر الرسائل القصيرة",
        "via_email": "عبر البريد الالكتروني",
        "please_enter_your_pin_code": "الرجاء إدخال الرمز السري الخاص بك",
        "enter_password": "أدخل كلمة المرور",
        "enter_email": "أدخل البريد الإلكتروني",
        "please_enter_a_valid_email_address":
            "يرجى إدخال عنوان بريد إلكتروني صالح",
        "reset_your_password_here": "إعادة تعيين كلمة المرور الخاصة\n بك هنا",
        "enter_your_new_password": "أدخل كلمة المرور الجديدة",
        "new_password": "كلمة المرور الجديدة",
        "please_enter_new_password": "الرجاء إدخال كلمة المرور الجديدة",
        "password_must_be_atleast_8_characters_long":
            "يجب أن تتكون كلمة المرور من 8 أحرف على الأقل",
        "password_not_match": "كلمة المرور غير متطابقة",
        "confirm_password": "تأكيد كلمة المرور",
        "find_your_comfort": "ابحث عن راحتك",
        "food_here": "الطعام هنا",
        "here_you_can_find_a_chef_or_dish_for_every":
            "هنا يمكنك العثور على طاهٍ أو طبق لكل شخص",
        "taste_and_color_enjoy": "!الطعم واللون.استمتع",
        "food_ninja_is_where_your": "فود نينجا هو المكان الذي تفضله",
        "comfort_food_lives": "حياة الطعام المريحة",
        "enjoy_a_fast_and_smooth_food_delivery_at":
            "استمتع بتوصيل سريع وسلس للطعام في",
        "your_doorstep": "عتبة داركم",
        "shipping": "شحن",
        "place_my_order": "ضع طلبي",
        "sub_total": "المجموع الفرعي",
        "delivery_charge": "رسوم التوصيل",
        "discount": "تخفيض",
        "total": "المجموع",
        "order_details": "تفاصيل الطلب",
        "confirm_order": "أكد الطلب",
        "deliver_to": "يسلم إلى",
        "edit": "يحرر",
        "payment": "قسط",
        "order_location": "موقع الطلب",
        "ringing": "...رنين",
        "okay_i_m_waiting": "حسنا انا انتظر",
        "thank_you_order_completed": "شكرًا لك! اكتمل الطلب",
        "thank_you_enjoy_your_meal": "شكرًا لك! أتمنى لك وجبة شهية",
        "please_rate_your_last_driver": "يرجى تقييم سائقك الأخير",
        "please_rate_your_food": "يرجى تقييم طعامك",
        "please_rate_your_restaurant": "يرجى تقييم مطعمك",
        "leave_feedback": "اترك تقييم للخدمة",
        "chat": "محادثة",
        "type": "يكتب",
        "location": "موقع",
        "food": "طعام",
        "search": "يبحث",
        "favorite": "مفضل",
        "proccess": "عملية",
        "find_your_favorite_food": "ابحث عن طعامك المفضل ",
        "what_do_you_want_to_order": "ماذا تريد أن تطلب؟",
        "nearest_restaurant": "أقرب مطعم",
        "view_more": "عرض المزيد",
        "popular_menu": "القائمة الشعبية",
        "view_all": "عرض الكل",
        "testimonials": "التوصيات",
        "popular": "شائع",
        "notification": "إشعار",
        "you_have": "لديك",
        "voucher": " فاتورة",
        "add_to_cart": "أضف إلى السلة",
        "popular_restaurant": "مطعم شعبي",
        "check_out": "الدفع",
        "voucher_promo": "قسيمة ترويجية",
        "home": "بيت",
        "profile": "حساب تعريفي",
        "cart": "عربة التسوق",
        "member_gold": "عضو ذهبي",
        "buy_again": "شراء مرة أخرى",
        "current_location": "الموقع الحالي",
        "form_gallery": "من المعرض ",
        "from_camera": "من الكاميرا",
        "enter_name": "أدخل الاسم",
        "code_send_to": " أرسل الكود إلى",
        "this_code_will_expired_in": " ستنتهي صلاحية هذا \n الرمز في",
        "submit": "يُقدِّم",
        "skip": "يتخطى",
        "added": "تمت الإضافة",
        "enter_message": "أدخل رسالة",
        "press_again_to_exit": "اضغط مرة أخرى للخروج"
      };

  static String getValues(String key) {
    if (Constant.language == 'ar') {
      return codeAr[key] ?? "";
    } else {
      return codeEn[key] ?? "";
    }
  }
}
